### ISSUE TITLE
About sollong Levels and Points Rewards

### ISSUE THREAD

**Issue by jsmzr** [hex-hook/coin-script#3]
| Level | points | Number Of People Invited | Rewards (Points) |
| -- | -- | -- | -- | 
| Titan | 49,616,939 | 221 | 250,000 |
| Vanguard | 7,394,899 | 185 | 100,000 |
| Conqueror | 2,767,564 | 154 | 50,000 |
| Diamond | 375,433 | 136 |	19,000 |
| Emerald | 118,247	| 86 | 6,000 |
| Platinum | 36,351 | 34 | 1,800 |
| Gold | 11,351 | 17 | 565 |
| Silver | 2,595 |11 | 130 |
| Bronze | 373 | 6 | 20 |
| Iron | 0 | 0 | 0 |

How do I get to the highest level?

**Comment by hex-hook** [comment]
First, you should sign in every day.
Second, you should invite enough users, if they also sign in tomorrow, then you will get more points reward.
Reaching **Emerald** is easy, but higher levels are very difficult. 
good luck.

**Comment by xingyaoc-1999** [comment]
I get 412 status code when I sign the message ,how to resolve it?

**Comment by hex-hook** [comment]
上了滑块验证码和限流
已经发了一波空投，被反撸了
